apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: inventory
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: kessel-inventory
    spec:
      envName: ${ENV_NAME}
#      testing:
#        iqePlugin: inventory_api
      deployments:
        - name: api
          replicas: 1
          podSpec:
            initContainers:
            - name: migration
              image: ${INVENTORY_IMAGE}:${INVENTORY_IMAGE_TAG}
              command: ["inventory-api"]
              args: ["migrate"]
              inheritEnv: true
            image: ${INVENTORY_IMAGE}:${INVENTORY_IMAGE_TAG}
            command: ["inventory-api"]
            args: ["serve"]
            livenessProbe:
              httpGet:
                path: /api/inventory/v1/livez
                port: 8081
            readinessProbe:
              httpGet:
                path: /api/inventory/v1/readyz
                port: 8081
            env:
            - name: INVENTORY_API_CONFIG
              value: "/inventory/inventory-api-config.yaml"
            volumeMounts:
                - name: config-volume
                  mountPath: "/inventory"
                - name: psks-volume
                  mountPath: /psks
            volumes:
              - name: config-volume
                secret:
                  secretName: inventory-api-config
              - name: psks-volume
                secret:
                  secretName: inventory-api-psks
          webServices:
            public:
              enabled: true
              apiPath: inventory
parameters:
  - description: ClowdEnvironment name (ephemeral, stage, prod)
    name: ENV_NAME
    required: true
  - description: App Image
    name: INVENTORY_IMAGE
    value: quay.io/redhat-services-prod/project-kessel-tenant/kessel-inventory/inventory-api
  - description: Image Tag
    name: INVENTORY_IMAGE_TAG
    value: latest
